### ISSUE TITLE
Design placeholder for remote image 

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/digital-mary#38]
When dealing with a record that showcases an item held in a collection (e.g., museum collection) but where a digital image is not yet available, the placeholder will take the place of that remote image.

**Comment by joeytakeda** [comment]
Done in commit https://github.com/joeytakeda/digital-mary/commit/9fb0d8055abcdb9008a921bb3a5bd7c84b5743ee

However, as I detail there, I've decided to take a bit of a simpler route: instead of designing a placeholder image, I've just made this into block of buttons (which basically look like another dropdown like the metadata or the inscription bits). One more remote images have been added to the site, we can discuss a nicer way to render them.

I've also made it such that if there is already an image associated with an item, you no longer have the option on the front-end to add a remote image--that's a brute force approach to ensuring that images and remote images are mutually exclusive, but I think it should suffice for the time being.
